;;; ride-apl-session-test.el --- M1 reducer tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'ride-apl-session)
(require 'ride-apl-proto)
(require 'ride-apl-test-common)

(ert-deftest ride-apl-session-init-opens-handshake ()
  (pcase-let ((`(,state . ,effects) (ride-apl-session-init)))
    (ert-info ("init should start in the handshake state")
      (should (equal (ride-apl-session-conn-state state) 'handshake)))
    (ert-info ("init should send both client handshake strings in order")
      (should (equal effects
                     (list (list :send (ride-apl-proto-handshake-supported))
                           (list :send (ride-apl-proto-handshake-using))))))))

(ert-deftest ride-apl-session-handshake-completion-sends-identify ()
  (pcase-dolist (`(,desc ,messages)
                 '(("spec order" (("SupportedProtocols" . "2")
                                  ("UsingProtocol" . "2")))
                   ("reversed order" (("UsingProtocol" . "2")
                                      ("SupportedProtocols" . "2")))
                   ("multi-valued supported list" (("SupportedProtocols" . "1,2")
                                                   ("UsingProtocol" . "2")))))
    (pcase-let ((`(,state . ,effects)
                 (ride-apl-test--fold (car (ride-apl-session-init)) messages)))
      (ert-info ((format "completing the handshake in %s should reach identifying" desc))
        (should (equal (ride-apl-session-conn-state state) 'identifying)))
      (ert-info ((format "completing the handshake in %s should send exactly one Identify" desc))
        (should (equal effects (list (list :send (ride-apl-proto-identify)))))))))

(ert-deftest ride-apl-session-half-handshake-waits ()
  (pcase-let ((`(,state . ,effects)
               (ride-apl-session-step (car (ride-apl-session-init))
                                  '("SupportedProtocols" . "2"))))
    (ert-info ("one handshake string should not advance past handshake")
      (should (equal (ride-apl-session-conn-state state) 'handshake)))
    (ert-info ("one handshake string should produce no effects")
      (should (equal effects nil)))))

(ert-deftest ride-apl-session-protocol-mismatch-dies ()
  (pcase-dolist (`(,desc ,message)
                 '(("unsupported protocol list" ("SupportedProtocols" . "1,3"))
                   ("wrong protocol in use" ("UsingProtocol" . "3"))))
    (pcase-let ((`(,state . ,effects)
                 (ride-apl-session-step (car (ride-apl-session-init)) message)))
      (ert-info ((format "%s should move the session to dead" desc))
        (should (equal (ride-apl-session-conn-state state) 'dead)))
      (ert-info ((format "%s should emit session-died naming the received string" desc))
        (should (equal effects
                       (list (list :session-died :protocol-mismatch
                                   (cdr message)))))))))

(ert-deftest ride-apl-session-identify-reply-connects ()
  (pcase-let ((`(,state . ,effects)
               (ride-apl-test--fold (car (ride-apl-session-init))
                                '(("SupportedProtocols" . "2")
                                  ("UsingProtocol" . "2")
                                  ("ReplyIdentify" . ((apiVersion . 1)
                                                      (version . "20.0")
                                                      (platform . "Linux-64")))))))
    (ert-info ("ReplyIdentify should reach the connected state")
      (should (equal (ride-apl-session-conn-state state) 'connected)))
    (ert-info ("ReplyIdentify should record the negotiated apiVersion")
      (should (equal (ride-apl-session-api-version state) 1)))
    (ert-info ("ReplyIdentify should store interpreter details")
      (should (equal (alist-get 'platform (ride-apl-session-interpreter state))
                     "Linux-64")))
    (ert-info ("reaching connected should send Connect then GetLog then SetPW")
      (should (equal (nthcdr (- (length effects) 3) effects)
                     (list (list :send (ride-apl-proto-connect))
                           (list :send (ride-apl-proto-get-log ride-apl-session-log-lines))
                           (list :send (ride-apl-proto-set-pw 80))))))))

(ert-deftest ride-apl-session-teardown-messages-die ()
  (pcase-dolist (`(,desc ,message ,reason)
                 '(("clean disconnect" ("Disconnect" . ((message . "bye")))
                    :disconnect)
                   ("interpreter crash" ("SysError" . ((text . "boom")))
                    :sys-error)))
    (pcase-let ((`(,state . ,effects)
                 (ride-apl-session-step (ride-apl-test--connected-session) message)))
      (ert-info ((format "%s should move the session to dead" desc))
        (should (equal (ride-apl-session-conn-state state) 'dead)))
      (ert-info ((format "%s should emit session-died with reason %s" desc reason))
        (should (equal (car (car effects)) :session-died))
        (should (equal (cadr (car effects)) reason))))))

(ert-deftest ride-apl-session-timeout-only-kills-pending-states ()
  (ert-info ("timeout during handshake should kill the session")
    (pcase-let ((`(,state . ,effects)
                 (ride-apl-session-step (car (ride-apl-session-init)) '(:timeout))))
      (should (equal (ride-apl-session-conn-state state) 'dead))
      (should (equal effects (list (list :session-died :timeout))))))
  (ert-info ("timeout after connect should be ignored")
    (pcase-let ((`(,state . ,effects)
                 (ride-apl-session-step (ride-apl-test--connected-session) '(:timeout))))
      (should (equal (ride-apl-session-conn-state state) 'connected))
      (should (equal effects nil)))))

(ert-deftest ride-apl-session-error-messages-notify ()
  (pcase-dolist (`(,desc ,message ,level)
                 '(("unknown command echo"
                    ("UnknownCommand" . ((name . "FancyStuff")))
                    :warn)
                   ("internal interpreter error"
                    ("InternalError" . ((error . 16) (error_text . "NONCE")))
                    :error)))
    (pcase-let ((`(,state . ,effects)
                 (ride-apl-session-step (ride-apl-test--connected-session) message)))
      (ert-info ((format "%s should not change the connection state" desc))
        (should (equal (ride-apl-session-conn-state state) 'connected)))
      (ert-info ((format "%s should notify at level %s" desc level))
        (should (equal (ride-apl-test--effect-types effects) (list :notify)))
        (should (equal (cadr (car effects)) level))))))

(ert-deftest ride-apl-session-caption-is-stored ()
  (pcase-let ((`(,state . ,effects)
               (ride-apl-session-step (ride-apl-test--connected-session)
                                  '("UpdateSessionCaption"
                                    . ((text . "CLEAR WS - Dyalog APL"))))))
    (ert-info ("UpdateSessionCaption should store the caption text")
      (should (equal (ride-apl-session-caption state) "CLEAR WS - Dyalog APL")))
    (ert-info ("UpdateSessionCaption should produce no effects")
      (should (equal effects nil)))))

(ert-deftest ride-apl-session-display-name-is-stored ()
  (pcase-let ((`(,state . ,effects)
               (ride-apl-session-step (ride-apl-test--connected-session)
                                  '("UpdateDisplayName"
                                    . ((displayName . "CLEAR WS"))))))
    (ert-info ("UpdateDisplayName should store the new name")
      (should (equal (ride-apl-session-display-name state) "CLEAR WS")))
    (ert-info ("UpdateDisplayName should produce no effects")
      (should (equal effects nil)))))

(ert-deftest ride-apl-session-unknown-messages-are-debug-noise ()
  (pcase-let ((`(,state . ,effects)
               (ride-apl-session-step (ride-apl-test--connected-session)
                                  '("FutureFeature" . ((x . 1))))))
    (ert-info ("an unknown message should not change the connection state")
      (should (equal (ride-apl-session-conn-state state) 'connected)))
    (ert-info ("an unknown message should surface only as a debug notify")
      (should (equal (ride-apl-test--effect-types effects) (list :notify)))
      (should (equal (cadr (car effects)) :debug)))))

(ert-deftest ride-apl-session-connection-loss-dies-once ()
  (ert-info ("a closed connection should kill a live session with the reason")
    (pcase-let ((`(,state . ,effects)
                 (ride-apl-session-step (ride-apl-test--connected-session)
                                    '(:closed "connection broken"))))
      (should (equal (ride-apl-session-conn-state state) 'dead))
      (should (equal effects
                     (list (list :session-died :connection-lost
                                 "connection broken"))))))
  (ert-info ("a closed connection on a dead session should be silent")
    (let ((dead (car (ride-apl-session-step (ride-apl-test--connected-session)
                                        '("Disconnect" . nil)))))
      (should (equal (cdr (ride-apl-session-step dead '(:closed "x"))) nil)))))

(ert-deftest ride-apl-session-dead-sessions-ignore-messages ()
  (let ((dead (car (ride-apl-session-step (ride-apl-test--connected-session)
                                      '("Disconnect" . nil)))))
    (pcase-dolist (`(,desc ,message)
                   '(("late output" ("AppendSessionOutput" . ((result . "x"))))
                     ("late disconnect" ("Disconnect" . nil))
                     ("timeout" (:timeout))))
      (pcase-let ((`(,state . ,effects) (ride-apl-session-step dead message)))
        (ert-info ((format "a dead session should ignore %s" desc))
          (should (equal (ride-apl-session-conn-state state) 'dead))
          (should (equal effects nil)))))))

(provide 'ride-apl-session-test)
;;; ride-apl-session-test.el ends here
