;;; ride-apl-session-repl-test.el --- M2 reducer tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'ride-apl-session)
(require 'ride-apl-proto)
(require 'ride-apl-test-common)

(defun ride-apl-repl-test--connected ()
  "Connected session, log backfill still pending."
  (car (ride-apl-test--fold (car (ride-apl-session-init))
                        '(("SupportedProtocols" . "2")
                          ("UsingProtocol" . "2")
                          ("ReplyIdentify" . ((apiVersion . 1)))))))

(defun ride-apl-repl-test--ready ()
  "Connected session with backfill done and an open prompt."
  (car (ride-apl-test--fold (ride-apl-repl-test--connected)
                        '(("ReplyGetLog" . ((result . nil)))
                          ("SetPromptType" . ((type . 1)))))))

(ert-deftest ride-apl-session-connect-requests-log-and-width ()
  (pcase-let ((`(,state . ,effects)
               (ride-apl-test--fold (car (ride-apl-session-init))
                                '(("SupportedProtocols" . "2")
                                  ("UsingProtocol" . "2")
                                  ("ReplyIdentify" . ((apiVersion . 1)))))))
    (ert-info ("connecting should send Identify, Connect, GetLog, SetPW in order")
      (should (equal effects
                     (list (list :send (ride-apl-proto-identify))
                           (list :send (ride-apl-proto-connect))
                           (list :send (ride-apl-proto-get-log ride-apl-session-log-lines))
                           (list :send (ride-apl-proto-set-pw (ride-apl-session-pw state)))))))
    (ert-info ("connecting should start waiting for the log backfill")
      (should (equal (ride-apl-session-log-state state) 'waiting)))))

(ert-deftest ride-apl-session-live-output-waits-for-backfill ()
  (pcase-let ((`(,state . ,effects)
               (ride-apl-session-step (ride-apl-repl-test--connected)
                                  '("AppendSessionOutput"
                                    . ((result . "early") (type . 2) (group . 0))))))
    (ert-info ("live output before ReplyGetLog should produce no display effect")
      (should (equal effects nil)))
    (ert-info ("live output before ReplyGetLog should be queued in state")
      (should (equal (ride-apl-session-queued-output state)
                     '(("early" 2 0)))))))

(ert-deftest ride-apl-session-backfill-renders-log-then-queue ()
  (pcase-let ((`(,state . ,effects)
               (ride-apl-test--fold
                (ride-apl-repl-test--connected)
                '(("AppendSessionOutput" . ((result . "live-1") (type . 2) (group . 0)))
                  ("ReplyGetLog"
                   . ((result . (((text . "log-1") (type . 2) (group . 7))
                                 "log-2"))))))))
    (ert-info ("log entries arrive newline-less; display should add one per line")
      (should (equal effects
                     '((:display-output "log-1\n" 2 7)
                       (:display-output "log-2\n" 2 0)
                       (:display-output "live-1" 2 0)))))
    (ert-info ("after backfill the queue should be empty and the log done")
      (should (equal (ride-apl-session-log-state state) 'done))
      (should (equal (ride-apl-session-queued-output state) nil)))
    (ert-info ("output after backfill should display immediately")
      (should (equal (cdr (ride-apl-session-step
                           state '("AppendSessionOutput"
                                   . ((result . "after") (type . 5) (group . 0)))))
                     '((:display-output "after" 5 0)))))))

(ert-deftest ride-apl-session-log-timeout-flushes ()
  (pcase-let ((`(,state . ,effects)
               (ride-apl-test--fold
                (ride-apl-repl-test--connected)
                '(("AppendSessionOutput" . ((result . "live-1") (type . 2) (group . 0)))
                  (:log-timeout)))))
    (ert-info ("a log timeout should flush queued output and note the timeout")
      (should (equal (car effects) '(:notify :debug "Log backfill timed out")))
      (should (member '(:display-output "live-1" 2 0) effects)))
    (ert-info ("a log timeout should mark the backfill done")
      (should (equal (ride-apl-session-log-state state) 'done))))
  (ert-info ("a late log timeout after ReplyGetLog should be ignored")
    (should (equal (cdr (ride-apl-session-step (ride-apl-repl-test--ready) '(:log-timeout)))
                   nil))))

(ert-deftest ride-apl-session-prompt-type-restyles-input ()
  (pcase-dolist (`(,type) '((0) (1) (2) (3) (4) (5)))
    (pcase-let ((`(,state . ,effects)
                 (ride-apl-session-step (ride-apl-repl-test--ready)
                                    `("SetPromptType" . ((type . ,type))))))
      (ert-info ((format "SetPromptType %d should be stored and emitted" type))
        (should (equal (ride-apl-session-prompt-type state) type))
        (should (equal effects (list (list :set-prompt type))))))))

(ert-deftest ride-apl-session-input-sends-when-ready ()
  (pcase-let ((`(,state . ,effects)
               (ride-apl-session-step (ride-apl-repl-test--ready) '(:input ("2+2")))))
    (ert-info ("input at an open prompt should send Execute with the six-space indent")
      (should (equal effects
                     (list (list :send (ride-apl-proto-execute "      2+2\n" 0))))))
    (ert-info ("sending a line should close the prompt locally until the interpreter reopens it")
      (should (equal (ride-apl-session-prompt-type state) 0)))
    (ert-info ("a single sent line should leave the pending queue empty")
      (should (equal (ride-apl-session-pending-lines state) nil)))))

(ert-deftest ride-apl-session-multi-line-input-drains-one-at-a-time ()
  (pcase-let ((`(,state . ,effects)
               (ride-apl-session-step (ride-apl-repl-test--ready) '(:input ("1+1" "2+2")))))
    (ert-info ("multi-line input should send only the first line")
      (should (equal effects
                     (list (list :send (ride-apl-proto-execute "      1+1\n" 0)))))
      (should (equal (ride-apl-session-pending-lines state) '("2+2"))))
    (pcase-let ((`(,state2 . ,effects2)
                 (ride-apl-session-step state '("SetPromptType" . ((type . 1))))))
      (ert-info ("a reopened prompt should send the next pending line")
        (should (member (list :send (ride-apl-proto-execute "      2+2\n" 0)) effects2))
        (should (equal (ride-apl-session-pending-lines state2) nil))))))

(ert-deftest ride-apl-session-input-respects-gates ()
  (ert-info ("input during a busy prompt should queue without sending")
    (let ((busy (car (ride-apl-session-step (ride-apl-repl-test--ready)
                                        '("SetPromptType" . ((type . 0)))))))
      (pcase-let ((`(,state . ,effects) (ride-apl-session-step busy '(:input ("2+2")))))
        (should (equal effects nil))
        (should (equal (ride-apl-session-pending-lines state) '("2+2"))))))
  (ert-info ("input during the log backfill should queue even at an open prompt")
    (let ((waiting (car (ride-apl-session-step (ride-apl-repl-test--connected)
                                           '("SetPromptType" . ((type . 1)))))))
      (pcase-let ((`(,state . ,effects) (ride-apl-session-step waiting '(:input ("2+2")))))
        (should (equal effects nil))
        (should (equal (ride-apl-session-pending-lines state) '("2+2")))))))

(ert-deftest ride-apl-session-quad-input-is-verbatim ()
  (let ((quad (car (ride-apl-session-step (ride-apl-repl-test--ready)
                                      '("SetPromptType" . ((type . 2)))))))
    (ert-info ("input at a quad prompt should be sent verbatim without indent")
      (should (equal (cdr (ride-apl-session-step quad '(:input ("'hi'"))))
                     (list (list :send (ride-apl-proto-execute "'hi'\n" 0))))))))

(ert-deftest ride-apl-session-had-error-clears-queue ()
  (let ((loaded (car (ride-apl-session-step (ride-apl-repl-test--ready)
                                        '(:input ("bad" "next-1" "next-2"))))))
    (pcase-let ((`(,state . ,effects) (ride-apl-session-step loaded '("HadError" . nil))))
      (ert-info ("HadError should clear the pending-line queue")
        (should (equal (ride-apl-session-pending-lines state) nil)))
      (ert-info ("HadError should ask the UI to focus the session")
        (should (equal effects '((:focus-repl))))))))

(ert-deftest ride-apl-session-interrupts-bypass-the-queue ()
  (let ((loaded (car (ride-apl-session-step (ride-apl-repl-test--ready)
                                        '(:input ("slow" "queued"))))))
    (pcase-dolist (`(,kind ,payload)
                   `((:weak ,(ride-apl-proto-weak-interrupt))
                     (:strong ,(ride-apl-proto-strong-interrupt))))
      (pcase-let ((`(,state . ,effects)
                   (ride-apl-session-step loaded `(:interrupt ,kind))))
        (ert-info ((format "a %s interrupt should be sent immediately while busy" kind))
          (should (equal effects (list (list :send payload)))))
        (ert-info ((format "a %s interrupt should not disturb the pending queue" kind))
          (should (equal (ride-apl-session-pending-lines state) '("queued"))))))))

(ert-deftest ride-apl-session-set-pw-command ()
  (ert-info ("a set-pw event should send SetPW and remember the width")
    (pcase-let ((`(,state . ,effects)
                 (ride-apl-session-step (ride-apl-repl-test--ready) '(:set-pw 132))))
      (should (equal effects (list (list :send (ride-apl-proto-set-pw 132)))))
      (should (equal (ride-apl-session-pw state) 132)))))


(ert-deftest ride-apl-session-log-drops-trailing-empty-string-entry ()
  (pcase-let ((`(,_ . ,effects)
               (ride-apl-test--fold
                (ride-apl-repl-test--connected)
                '(("ReplyGetLog" . ((result . ("banner" ""))))))))
    (ert-info ("a trailing empty string entry should not render a blank line")
      (should (equal effects '((:display-output "banner\n" 2 0)))))))

(ert-deftest ride-apl-session-line-group-message-is-consumed ()
  (pcase-let ((`(,state . ,effects)
               (ride-apl-test--fold
                (ride-apl-repl-test--connected)
                '(("ReplyGetLog" . ((result . ())))
                  ("SetPromptType" . ((type . 1)))
                  ("SetSessionLineGroup" . ((line_offset . 1) (group . 3)))))))
    (ert-info ("SetSessionLineGroup should be consumed without a debug notify")
      (should (null (seq-filter (lambda (e) (eq (car e) :notify)) effects))))
    (ert-info ("SetSessionLineGroup should leave the session usable")
      (should (equal (ride-apl-session-prompt-type state) 1)))))

(provide 'ride-apl-session-repl-test)
;;; ride-apl-session-repl-test.el ends here
